### ISSUE TITLE
Album artwork not injecting / showing on 1.1.40.508.gd5bc2931

### ISSUE THREAD

**Issue by 3raxton** [w0lfschild/spotifyPlus#11]
Hey there,

Great work on spotifyPlus, I love how it enhances my Spotify experience. After updating to 1.1.40.508.gd5bc2931, the tweak does not seem to be injecting as no album artwork is showing. I don't have a crash log with this as I couldn't find one; however, if there is anything further needed, I'd be more than happy to share any info I can! 

Thanks!

**Comment by w0lfschild** [comment]
Not sure what the issue is for you but try updating to the latest versions 

MacForge : https://github.com/w0lfschild/app_updates/raw/master/MacForge1/MacForge.zip
spotifyPlus : https://github.com/MacEnhance/MacForgeRepo/raw/master/repo/bundles/spotifyPlus_0.9.2.zip

![Screen Shot 2020-08-24 at 5 11 19 PM](https://user-images.githubusercontent.com/1920148/91108403-d97cb680-e62c-11ea-98d9-af3e1d41054e.png)

**Comment by 3raxton** [comment]
Thanks for sharing this, I had no idea MacForge had an update which helped me clear this up along with a restart. Keep up the great work, I couldn't live without these tweaks!
