### ISSUE TITLE
Spotify app doesn

### ISSUE THREAD

**Issue by jingan0904** [w0lfschild/spotifyPlus#7]

**Comment by w0lfschild** [comment]
Doesn't what?

**Comment by jingan0904** [comment]
Sorry somehow pressed the wrong button.

My Spotify app now doesnt work for some reason. 
Any methods to determine the cause of the problem

**Comment by Fofer** [comment]
I am running spotifyPlus (with mySIMBL and macOS 10.13.3) and my Spotify app works fine.  So if you're asking for "any methods to determine the cause of the problem" the first step would be to disable spotifyPlus, and then relaunch Spotify and see if the problem goes away for you.  More information about your installation (OS version, any other add-ons installed, etc.) would need to be known about your system before being able to help you troubleshoot effectively.

**Comment by jingan0904** [comment]
I have tried disabling spotifyPlus still cannot start stuck with the spinning wheel of spotify.
Spotify has worked since quite a long time, suddenly just crashed and stopped working.
OS version: 10.13 Beta(17A344b)

**Comment by Fofer** [comment]
Since you've disabled spotifyPlus and are still experiencing the problem, your issue has nothing to do with spotifyPlus, and doesn't warrant being discussed here.

I'd recommend you delete your Spotify app, and then download and re-install a fresh new version: https://www.spotify.com/us/download/other/

I'd also  recommend you update macOS beyond that old beta.  The current release is 10.13.3.

**Comment by jingan0904** [comment]
I redownloaded multiple times but it still does not work.
I will try to find the update ASAP

**Comment by w0lfschild** [comment]
@TechnoTew sounds like you might be having some other issues. It's possible maybe another mySIMBL plugin is causing issues but spotifyPlus is unlikely to be what's causing the problems.

**Comment by jingan0904** [comment]
I have disabled the rest of the plugins and still having the same problem, need to backup my mac and then update and try again.
Thanks for the help up to now.
Will get back to you ASAP

**Comment by Fofer** [comment]
If you disabled the rest of your SIMBL plugins and the problem persists than then problem has nothing to do with those plugins.  Your issue has to do with Spotify and macOS, period, and your bug reports belong on the support sites of those two products.  Although I doubt either will help you, since you're running beta macOS.

In order to update beyond macOS beta to a release you will likely need to unenroll from the beta first.  https://www.imore.com/how-opt-out-macos-high-sierra-beta-program

If your storage device is a hard drive instead of an SSD, you will need to backup everything, format your drive and restore from your backup, since the ultimate release of High Sierra dropped APFS support for spinning hard drives and only works on SSD's, for now.

It's best that you understand how the macOS beta program works and be careful about installing it on any primary Mac, because it can and will lead to problems for you, and if you're not capable of troubleshooting those problems, the problems can get worse.  You may want to reconsider even being on the beta program in the first place.

Good luck!

**Comment by jingan0904** [comment]
Finally managed to fix my dumb mac and the spotify works now, thx guys for helping
